const formatter = new Intl.NumberFormat('pt-BR');
const periodSelect = document.querySelector('#period');
const metricGrid = document.querySelector('#metric-grid');
const actionList = document.querySelector('#action-list');
const informativeTable = document.querySelector('#informative-table');
const partnerTable = document.querySelector('#partner-table');
const locationList = document.querySelector('#location-list');
const menuToggle = document.querySelector('#menu-toggle');
const sidebar = document.querySelector('#sidebar');

function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function renderMetrics(data){const visits=data.metrics.visits,today=data.visits.length?data.visits.at(-1).value:0,percent=value=>visits?Math.round(value/visits*100):0;const rows=[['VIS','Visitas no site',visits,`${formatter.format(today)} hoje`,'#08abe0','#e7f8fe'],['30s','Viram 30s do vídeo',data.metrics.video30,`${percent(data.metrics.video30)}% das visitas`,'#f5841f','#fff1e5'],['PDF','Downloads de informativos',data.metrics.downloads,`${data.info.length} materiais`,'#284a9b','#eaf0ff'],['ON','Informativos online',data.metrics.onlineViews,`${data.info.length} páginas`,'#00ad35','#e5f8eb'],['PAR','Cliques em parceiros',data.metrics.partnerClicks,`${percent(data.metrics.partnerClicks)}% das visitas`,'#ffd100','#fff8d8'],['COL','Colinhas concluídas',data.metrics.completedBallots,'Principal + parceiros','#08abe0','#e7f8fe'],['RED','Cliques nas redes',data.metrics.socialClicks,'Redes da campanha','#f5841f','#fff1e5'],['TIM','Acessos ao Time Luciano',data.metrics.teamClicks,`${percent(data.metrics.teamClicks)}% das visitas`,'#284a9b','#eaf0ff']];metricGrid.innerHTML=rows.map(([icon,label,value,detail,color,soft])=>`<article class="metric-card" style="--accent:${color};--accent-soft:${soft}"><span class="metric-icon">${icon}</span><p class="metric-label">${label}</p><p class="metric-value">${formatter.format(value)}</p><p class="metric-detail">${detail}</p></article>`).join('')}
function renderChart(data){const input=data.visits.map(item=>item.value),values=input.length?input:[0,0];if(values.length===1)values.push(values[0]);const width=760,height=260,padX=38,padY=25,max=Math.max(...values,1),min=Math.min(...values,0),span=Math.max(1,max-min);const points=values.map((value,index)=>[padX+(index/(values.length-1))*(width-padX*2),height-padY-((value-min)/span)*(height-padY*2)]);const line=points.map(([x,y],index)=>`${index?'L':'M'} ${x.toFixed(1)} ${y.toFixed(1)}`).join(' '),area=`${line} L ${points.at(-1)[0]} ${height-padY} L ${points[0][0]} ${height-padY} Z`;const grid=[0,1,2,3].map(step=>{const y=padY+step*((height-padY*2)/3);return `<line class="grid-line" x1="${padX}" y1="${y}" x2="${width-padX}" y2="${y}"/>`}).join('');const indexes=[0,Math.floor((values.length-1)/2),values.length-1],labels=indexes.map((index,pos)=>`<text class="axis-label" x="${points[index][0]}" y="250" text-anchor="middle">${pos===0?'Início':pos===2?'Hoje':'Meio do período'}</text>`).join(''),dots=indexes.map(index=>`<circle class="chart-point" cx="${points[index][0]}" cy="${points[index][1]}" r="5"/>`).join('');document.querySelector('#visits-chart').innerHTML=`<defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#08abe0" stop-opacity=".28"/><stop offset="1" stop-color="#08abe0" stop-opacity="0"/></linearGradient></defs>${grid}<path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/>${dots}${labels}`;document.querySelector('#chart-total').textContent=formatter.format(data.metrics.visits);const sign=data.trend>=0?'+':'';document.querySelector('#chart-trend').textContent=`${sign}${Number(data.trend).toFixed(1).replace('.',',')}% em relação ao período anterior`}
function renderActions(rows){const max=Math.max(...rows.map(([,value])=>value),1);actionList.innerHTML=rows.map(([label,value])=>`<div class="action-row"><strong>${escapeHtml(label)}</strong><b>${formatter.format(value)}</b><div class="bar"><span style="width:${Math.round(value/max*100)}%"></span></div></div>`).join('')}
function renderInfo(rows){informativeTable.innerHTML=rows.length?rows.map(([name,views,downloads],index)=>`<tr><td><span class="rank">${String(index+1).padStart(2,'0')}</span><strong>${escapeHtml(name)}</strong></td><td>${formatter.format(views)}</td><td>${formatter.format(downloads)}</td><td><span class="total-pill">${formatter.format(views+downloads)}</span></td></tr>`).join(''):'<tr><td colspan="4" class="empty-cell">Ainda não há dados neste período.</td></tr>'}
function renderPartners(rows){partnerTable.innerHTML=rows.length?rows.map(([name,ballots,shares],index)=>`<tr><td><span class="rank">${String(index+1).padStart(2,'0')}</span><strong>${escapeHtml(name)}</strong></td><td>${formatter.format(ballots)}</td><td><span class="total-pill">${formatter.format(shares)}</span></td></tr>`).join(''):'<tr><td colspan="3" class="empty-cell">Ainda não há dados neste período.</td></tr>'}
function renderLocations(rows){if(!rows.length){locationList.innerHTML='<p class="empty-state">Ainda não há região aproximada disponível.</p>';return}const max=Math.max(...rows.map(([, ,value])=>value),1);locationList.innerHTML=rows.map(([name,state,value])=>`<div class="location-row"><div class="location-name"><strong>${escapeHtml(name)}</strong><span>${escapeHtml(state)}</span></div><div class="location-value">${formatter.format(value)}</div><div class="bar"><span style="width:${Math.round(value/max*100)}%"></span></div></div>`).join('')}
async function load(){document.querySelector('#data-status').textContent='Atualizando';try{const response=await fetch(`api.php?days=${periodSelect.value}`,{cache:'no-store'});if(response.status===401){location.reload();return}const data=await response.json();if(!response.ok)throw new Error('Não foi possível atualizar.');renderMetrics(data);renderChart(data);renderActions(data.actions);renderInfo(data.info);renderPartners(data.partners);renderLocations(data.locations);document.querySelector('#data-status').textContent='Dados reais';document.querySelector('#updated-at').textContent=data.generatedAt?`Atualizado em ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(data.generatedAt))}`:'Coleta iniciada · aguardando as primeiras visitas'}catch(error){document.querySelector('#data-status').textContent='Falha na atualização';document.querySelector('#updated-at').textContent=error.message}}
periodSelect.addEventListener('change',load);menuToggle.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.sidebar nav a').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.sidebar nav a').forEach(item=>item.classList.remove('active'));link.classList.add('active');sidebar.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));load();
